apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: owyz3soof-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: owyz3soof-go 
  name: owyz3soof-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: owyz3soof-go 
